Feat/mfc 83 permettre dupdate le nickname dune game
LSDAF/lsdaf_backend pull request #18
Opened 2024-09-25 19:22 UTC by adufou

2024-09-27 11:38 UTC, adufou commented
J'ai eu un bug en cliquant sur generer une save dans le client, vérifier ce qu'il se passe quand on ne fournit pas de nickname (devrait accepter, et mettre player, c'est le contrat de base)

2024-09-27 12:41 UTC, louis-santucci commented
Que se passera-t-il si le user crée plusieurs games sans précisant de nickname?

2024-09-27 12:50 UTC, louis-santucci commented
(Pour pas se faire chier, on peut prendre par exemple prendre les derniers caractères de l'UUID de la game save, plutôt que de devoir régénérer un bail (voir TokenUtils.java, y'a un générateur de token random), a voir ce que tu préfères)

2024-09-27 12:53 UTC, adufou commented
bien vu, j'implem ça dans la PR

2024-09-27 12:56 UTC, louis-santucci commented
(Dans l'objet GameSaveEntity, dans le @column, tu peux rajouter une property unique=true
Pour assurer que l'on ne peut pas ajouter deux game saves avec le même nickname.)

Après vas-y je me dis qu'il faut peut être que le Nickname soit unique PAR user, en mode c'est plutôt le couple (User, nickname) qui doit être unique, tajveudireoupas ?

Tu en penses quoi?

2024-09-27 13:02 UTC, adufou commented
Limiter les charactères autorisés + taille max

2024-09-27 19:50 UTC, louis-santucci requested changes

2024-09-27 19:50 UTC, louis-santucci commented on src/main/java/com/lsadf/lsadf_backend/entities/GameSaveEntity.java
> +    @Builder.Default
Tu peux supprimer @Builder.Default, c'est uniquement quand tu lui donnes une valeur direct sans passer par un constructeur

2024-09-27 19:50 UTC, louis-santucci commented on src/main/java/com/lsadf/lsadf_backend/services/impl/GameSaveServiceImpl.java
> +        GameSaveEntity savedEntity = gameSaveRepository.save(saved);
le repository.save() enregistre l'objet en base, donc tu dois set son nickname avant de faire le save(). Donc set le nickname, et save ensuite

2024-09-27 19:50 UTC, louis-santucci commented on src/main/java/com/lsadf/lsadf_backend/services/impl/GameSaveServiceImpl.java
> -        GameSaveEntity saved = gameSaveRepository.save(entity);
Same, tu dois save à la fin, sinon le nickname sera pas sauvegardé en base

2024-09-27 21:02 UTC, adufou commented on src/main/java/com/lsadf/lsadf_backend/services/impl/GameSaveServiceImpl.java
> +        GameSaveEntity savedEntity = gameSaveRepository.save(saved);
Justement, j'ai fait ça au début mais l'id est pas défini avant save.

Est-ce que je save 2 fois ?

2024-09-27 21:02 UTC, adufou commented on src/main/java/com/lsadf/lsadf_backend/services/impl/GameSaveServiceImpl.java
> +        GameSaveEntity savedEntity = gameSaveRepository.save(saved);
Sinon on génère différement le nickname

2024-09-27 21:03 UTC, adufou commented on src/test/java/com/lsadf/lsadf_backend/bdd/then/BddThenStepDefinitions.java
> +                    .ignoringExpectedNullFields()
j'ai rajouté des `.ignoringExpectedNullFields()`, est-ce que t'es contre ?

2024-09-27 21:06 UTC, adufou commented on src/main/java/com/lsadf/lsadf_backend/entities/GameSaveEntity.java
> +    @Column(name = EntityAttributes.GameSave.GAME_SAVE_NICKNAME, unique = true)
J'ai l'impression que ça ça empêche pas d'update en non unique, j'ai du faire les modif dans `src/main/java/com/lsadf/lsadf_backend/services/impl/GameSaveServiceImpl.java` pour gérer l'unicité.

C'est le comportement attendui ?

2024-09-27 21:13 UTC, louis-santucci commented on src/main/java/com/lsadf/lsadf_backend/services/impl/GameSaveServiceImpl.java
> +        GameSaveEntity savedEntity = gameSaveRepository.save(saved);
T'as déjà un save un peu plus haut

2024-09-27 21:13 UTC, louis-santucci commented on src/test/java/com/lsadf/lsadf_backend/bdd/then/BddThenStepDefinitions.java
> +                    .ignoringExpectedNullFields()
Je sais pas à quoi ca sert `.ignoringExpectedNullFields()`

2024-09-27 21:14 UTC, louis-santucci commented on src/main/java/com/lsadf/lsadf_backend/entities/GameSaveEntity.java
> +    @Column(name = EntityAttributes.GameSave.GAME_SAVE_NICKNAME, unique = true)
Dans les BDD on instancie des map qui remplacent les vraies tables SQL, ca marchera pas en cas réel

2024-09-27 21:15 UTC, louis-santucci commented on src/main/java/com/lsadf/lsadf_backend/entities/GameSaveEntity.java
> +    @Column(name = EntityAttributes.GameSave.GAME_SAVE_NICKNAME, unique = true)
(mdr)

2024-09-27 21:16 UTC, louis-santucci commented on src/main/java/com/lsadf/lsadf_backend/services/impl/GameSaveServiceImpl.java
> +        GameSaveEntity savedEntity = gameSaveRepository.save(saved);
ligne 58

2024-09-27 21:26 UTC, louis-santucci commented on src/main/java/com/lsadf/lsadf_backend/services/impl/GameSaveServiceImpl.java
> +        savedEntity.setNickname(entity.getId());
D'ailleurs, théoriquement t'es censé donner le nickname en paramètre non? T'es supposé l'avoir en input le nickname, du coup faut changer la signature de la méthode + celle de l'interface

2024-09-28 13:12 UTC, louis-santucci approved these changes

2024-09-28 13:12 UTC, merged